// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.0
// - protoc             v4.22.0
// source: common/common.proto

package common

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCommonPing = "/api.common.Common/Ping"

type CommonHTTPServer interface {
	Ping(context.Context, *Empty) (*PingResp, error)
}

func RegisterCommonHTTPServer(s *http.Server, srv CommonHTTPServer) {
	r := s.Route("/")
	r.GET("/ping", _Common_Ping0_HTTP_Handler(srv))
}

func _Common_Ping0_HTTP_Handler(srv CommonHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCommonPing)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Ping(ctx, req.(*Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PingResp)
		return ctx.Result(200, reply)
	}
}

type CommonHTTPClient interface {
	Ping(ctx context.Context, req *Empty, opts ...http.CallOption) (rsp *PingResp, err error)
}

type CommonHTTPClientImpl struct {
	cc *http.Client
}

func NewCommonHTTPClient(client *http.Client) CommonHTTPClient {
	return &CommonHTTPClientImpl{client}
}

func (c *CommonHTTPClientImpl) Ping(ctx context.Context, in *Empty, opts ...http.CallOption) (*PingResp, error) {
	var out PingResp
	pattern := "/ping"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCommonPing))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
