// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DiariesColumns holds the columns for the "diaries" table.
	DiariesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Size: 60},
		{Name: "deleted_at", Type: field.TypeInt64, Default: 0},
		{Name: "created_at", Type: field.TypeInt64, Default: 0},
		{Name: "updated_at", Type: field.TypeInt64, Default: 0},
		{Name: "title", Type: field.TypeString, Default: ""},
		{Name: "content", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "belong_at", Type: field.TypeInt64, Default: 0},
		{Name: "user_id", Type: field.TypeString, Default: ""},
		{Name: "tag", Type: field.TypeString, Default: "-"},
	}
	// DiariesTable holds the schema information for the "diaries" table.
	DiariesTable = &schema.Table{
		Name:       "diaries",
		Columns:    DiariesColumns,
		PrimaryKey: []*schema.Column{DiariesColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Size: 60},
		{Name: "deleted_at", Type: field.TypeInt64, Default: 0},
		{Name: "created_at", Type: field.TypeInt64, Default: 0},
		{Name: "updated_at", Type: field.TypeInt64, Default: 0},
		{Name: "account", Type: field.TypeString, Default: ""},
		{Name: "password", Type: field.TypeString, Default: ""},
		{Name: "password_salt", Type: field.TypeString, Default: ""},
		{Name: "name", Type: field.TypeString, Default: "unknown"},
		{Name: "mobile", Type: field.TypeString, Default: ""},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_account_deleted_at",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[4], UsersColumns[1]},
			},
			{
				Name:    "user_mobile_deleted_at",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[8], UsersColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DiariesTable,
		UsersTable,
	}
)

func init() {
}
