// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.22.0
// source: mini/diary/v1/diary.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "kratos-use/api/common"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteDiaryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteDiaryReq) Reset() {
	*x = DeleteDiaryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mini_diary_v1_diary_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDiaryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDiaryReq) ProtoMessage() {}

func (x *DeleteDiaryReq) ProtoReflect() protoreflect.Message {
	mi := &file_mini_diary_v1_diary_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDiaryReq.ProtoReflect.Descriptor instead.
func (*DeleteDiaryReq) Descriptor() ([]byte, []int) {
	return file_mini_diary_v1_diary_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteDiaryReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteDiaryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteDiaryResp) Reset() {
	*x = DeleteDiaryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mini_diary_v1_diary_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDiaryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDiaryResp) ProtoMessage() {}

func (x *DeleteDiaryResp) ProtoReflect() protoreflect.Message {
	mi := &file_mini_diary_v1_diary_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDiaryResp.ProtoReflect.Descriptor instead.
func (*DeleteDiaryResp) Descriptor() ([]byte, []int) {
	return file_mini_diary_v1_diary_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteDiaryResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateDiaryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title    string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content  string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	BelongAt int64  `protobuf:"varint,4,opt,name=belongAt,proto3" json:"belongAt,omitempty"`
	Tag      string `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *UpdateDiaryReq) Reset() {
	*x = UpdateDiaryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mini_diary_v1_diary_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDiaryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDiaryReq) ProtoMessage() {}

func (x *UpdateDiaryReq) ProtoReflect() protoreflect.Message {
	mi := &file_mini_diary_v1_diary_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDiaryReq.ProtoReflect.Descriptor instead.
func (*UpdateDiaryReq) Descriptor() ([]byte, []int) {
	return file_mini_diary_v1_diary_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateDiaryReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDiaryReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateDiaryReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateDiaryReq) GetBelongAt() int64 {
	if x != nil {
		return x.BelongAt
	}
	return 0
}

func (x *UpdateDiaryReq) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type UpdateDiaryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UpdateDiaryResp) Reset() {
	*x = UpdateDiaryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mini_diary_v1_diary_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDiaryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDiaryResp) ProtoMessage() {}

func (x *UpdateDiaryResp) ProtoReflect() protoreflect.Message {
	mi := &file_mini_diary_v1_diary_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDiaryResp.ProtoReflect.Descriptor instead.
func (*UpdateDiaryResp) Descriptor() ([]byte, []int) {
	return file_mini_diary_v1_diary_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateDiaryResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateDiaryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title    string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content  string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	BelongAt int64  `protobuf:"varint,3,opt,name=belongAt,proto3" json:"belongAt,omitempty"`
	Tag      string `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *CreateDiaryReq) Reset() {
	*x = CreateDiaryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mini_diary_v1_diary_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDiaryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDiaryReq) ProtoMessage() {}

func (x *CreateDiaryReq) ProtoReflect() protoreflect.Message {
	mi := &file_mini_diary_v1_diary_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDiaryReq.ProtoReflect.Descriptor instead.
func (*CreateDiaryReq) Descriptor() ([]byte, []int) {
	return file_mini_diary_v1_diary_proto_rawDescGZIP(), []int{4}
}

func (x *CreateDiaryReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateDiaryReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateDiaryReq) GetBelongAt() int64 {
	if x != nil {
		return x.BelongAt
	}
	return 0
}

func (x *CreateDiaryReq) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type CreateDiaryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateDiaryResp) Reset() {
	*x = CreateDiaryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mini_diary_v1_diary_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDiaryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDiaryResp) ProtoMessage() {}

func (x *CreateDiaryResp) ProtoReflect() protoreflect.Message {
	mi := &file_mini_diary_v1_diary_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDiaryResp.ProtoReflect.Descriptor instead.
func (*CreateDiaryResp) Descriptor() ([]byte, []int) {
	return file_mini_diary_v1_diary_proto_rawDescGZIP(), []int{5}
}

func (x *CreateDiaryResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDiaryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetDiaryReq) Reset() {
	*x = GetDiaryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mini_diary_v1_diary_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDiaryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiaryReq) ProtoMessage() {}

func (x *GetDiaryReq) ProtoReflect() protoreflect.Message {
	mi := &file_mini_diary_v1_diary_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiaryReq.ProtoReflect.Descriptor instead.
func (*GetDiaryReq) Descriptor() ([]byte, []int) {
	return file_mini_diary_v1_diary_proto_rawDescGZIP(), []int{6}
}

func (x *GetDiaryReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDiaryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title     string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CreatedAt int64  `protobuf:"varint,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt int64  `protobuf:"varint,4,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Content   string `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	BelongAt  int64  `protobuf:"varint,6,opt,name=belongAt,proto3" json:"belongAt,omitempty"`
	Tag       string `protobuf:"bytes,7,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *GetDiaryResp) Reset() {
	*x = GetDiaryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mini_diary_v1_diary_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDiaryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiaryResp) ProtoMessage() {}

func (x *GetDiaryResp) ProtoReflect() protoreflect.Message {
	mi := &file_mini_diary_v1_diary_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiaryResp.ProtoReflect.Descriptor instead.
func (*GetDiaryResp) Descriptor() ([]byte, []int) {
	return file_mini_diary_v1_diary_proto_rawDescGZIP(), []int{7}
}

func (x *GetDiaryResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetDiaryResp) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetDiaryResp) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetDiaryResp) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *GetDiaryResp) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetDiaryResp) GetBelongAt() int64 {
	if x != nil {
		return x.BelongAt
	}
	return 0
}

func (x *GetDiaryResp) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type ListDiaryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int32  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Keywords string `protobuf:"bytes,3,opt,name=keywords,proto3" json:"keywords,omitempty"`
	StartAt  int64  `protobuf:"varint,4,opt,name=startAt,proto3" json:"startAt,omitempty"`
	EndAt    int64  `protobuf:"varint,5,opt,name=endAt,proto3" json:"endAt,omitempty"`
}

func (x *ListDiaryReq) Reset() {
	*x = ListDiaryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mini_diary_v1_diary_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDiaryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDiaryReq) ProtoMessage() {}

func (x *ListDiaryReq) ProtoReflect() protoreflect.Message {
	mi := &file_mini_diary_v1_diary_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDiaryReq.ProtoReflect.Descriptor instead.
func (*ListDiaryReq) Descriptor() ([]byte, []int) {
	return file_mini_diary_v1_diary_proto_rawDescGZIP(), []int{8}
}

func (x *ListDiaryReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDiaryReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDiaryReq) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

func (x *ListDiaryReq) GetStartAt() int64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

func (x *ListDiaryReq) GetEndAt() int64 {
	if x != nil {
		return x.EndAt
	}
	return 0
}

type ListDiaryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int32                `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*ListItemDiaryResp `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ListDiaryResp) Reset() {
	*x = ListDiaryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mini_diary_v1_diary_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDiaryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDiaryResp) ProtoMessage() {}

func (x *ListDiaryResp) ProtoReflect() protoreflect.Message {
	mi := &file_mini_diary_v1_diary_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDiaryResp.ProtoReflect.Descriptor instead.
func (*ListDiaryResp) Descriptor() ([]byte, []int) {
	return file_mini_diary_v1_diary_proto_rawDescGZIP(), []int{9}
}

func (x *ListDiaryResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListDiaryResp) GetList() []*ListItemDiaryResp {
	if x != nil {
		return x.List
	}
	return nil
}

type ListItemDiaryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title     string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CreatedAt int64  `protobuf:"varint,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt int64  `protobuf:"varint,4,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Desc      string `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	BelongAt  int64  `protobuf:"varint,6,opt,name=belongAt,proto3" json:"belongAt,omitempty"`
	Tag       string `protobuf:"bytes,7,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *ListItemDiaryResp) Reset() {
	*x = ListItemDiaryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mini_diary_v1_diary_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListItemDiaryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemDiaryResp) ProtoMessage() {}

func (x *ListItemDiaryResp) ProtoReflect() protoreflect.Message {
	mi := &file_mini_diary_v1_diary_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemDiaryResp.ProtoReflect.Descriptor instead.
func (*ListItemDiaryResp) Descriptor() ([]byte, []int) {
	return file_mini_diary_v1_diary_proto_rawDescGZIP(), []int{10}
}

func (x *ListItemDiaryResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListItemDiaryResp) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ListItemDiaryResp) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ListItemDiaryResp) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ListItemDiaryResp) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *ListItemDiaryResp) GetBelongAt() int64 {
	if x != nil {
		return x.BelongAt
	}
	return 0
}

func (x *ListItemDiaryResp) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

var File_mini_diary_v1_diary_proto protoreflect.FileDescriptor

var file_mini_diary_v1_diary_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6d, 0x69, 0x6e, 0x69, 0x2f, 0x64, 0x69, 0x61, 0x72, 0x79, 0x2f, 0x76, 0x31, 0x2f,
	0x64, 0x69, 0x61, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x61, 0x70, 0x69,
	0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x2e, 0x64, 0x69, 0x61, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x1a, 0x17,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x20, 0x0a, 0x0e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x44, 0x69, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x21, 0x0a, 0x0f,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x69, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x7e, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x61, 0x72, 0x79, 0x52, 0x65,
	0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x65, 0x6c, 0x6f, 0x6e, 0x67, 0x41, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x62, 0x65, 0x6c, 0x6f, 0x6e, 0x67, 0x41, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x61, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x22,
	0x21, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x61, 0x72, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x6e, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x69, 0x61, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x65, 0x6c, 0x6f, 0x6e, 0x67, 0x41, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x62, 0x65, 0x6c, 0x6f, 0x6e, 0x67, 0x41, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74,
	0x61, 0x67, 0x22, 0x21, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x69, 0x61, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1d, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x44, 0x69, 0x61, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0xb8, 0x01, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x44, 0x69, 0x61, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x65, 0x6c, 0x6f, 0x6e, 0x67, 0x41, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x62, 0x65, 0x6c, 0x6f, 0x6e, 0x67, 0x41, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x61, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x22,
	0x8a, 0x01, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x69, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6e, 0x64, 0x41, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x65, 0x6e, 0x64, 0x41, 0x74, 0x22, 0x5f, 0x0a, 0x0d,
	0x4c, 0x69, 0x73, 0x74, 0x44, 0x69, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x12, 0x38, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x2e, 0x64, 0x69, 0x61,
	0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x69,
	0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0xb7, 0x01,
	0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x69, 0x61, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x65, 0x6c,
	0x6f, 0x6e, 0x67, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x62, 0x65, 0x6c,
	0x6f, 0x6e, 0x67, 0x41, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x32, 0xae, 0x04, 0x0a, 0x05, 0x44, 0x69, 0x61, 0x72,
	0x79, 0x12, 0x65, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x69, 0x61, 0x72, 0x79, 0x12, 0x1f,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x2e, 0x64, 0x69, 0x61, 0x72, 0x79, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x69, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x1a,
	0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x2e, 0x64, 0x69, 0x61, 0x72, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x69, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x2f, 0x64, 0x69, 0x61, 0x72, 0x79, 0x12, 0x67, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x44,
	0x69, 0x61, 0x72, 0x79, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x2e,
	0x64, 0x69, 0x61, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x61, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x2e,
	0x64, 0x69, 0x61, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x61, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x12, 0x12, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x69, 0x61, 0x72, 0x79, 0x2f, 0x7b, 0x69, 0x64,
	0x7d, 0x12, 0x6e, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x69, 0x61, 0x72, 0x79,
	0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x2e, 0x64, 0x69, 0x61, 0x72,
	0x79, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x69, 0x61, 0x72, 0x79,
	0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x2e, 0x64,
	0x69, 0x61, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x69,
	0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x3a,
	0x01, 0x2a, 0x22, 0x0d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x69, 0x61, 0x72,
	0x79, 0x12, 0x73, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x61, 0x72, 0x79,
	0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x2e, 0x64, 0x69, 0x61, 0x72,
	0x79, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x61, 0x72, 0x79,
	0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x2e, 0x64,
	0x69, 0x61, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69,
	0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x3a,
	0x01, 0x2a, 0x1a, 0x12, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x69, 0x61, 0x72,
	0x79, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x70, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x44, 0x69, 0x61, 0x72, 0x79, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x69, 0x6e, 0x69,
	0x2e, 0x64, 0x69, 0x61, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x44, 0x69, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d,
	0x69, 0x6e, 0x69, 0x2e, 0x64, 0x69, 0x61, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x44, 0x69, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x22, 0x1a, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x14, 0x2a, 0x12, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x69,
	0x61, 0x72, 0x79, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x42, 0x21, 0x5a, 0x1f, 0x6b, 0x72, 0x61, 0x74,
	0x6f, 0x73, 0x2d, 0x75, 0x73, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x69, 0x6e, 0x69, 0x2f,
	0x64, 0x69, 0x61, 0x72, 0x79, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_mini_diary_v1_diary_proto_rawDescOnce sync.Once
	file_mini_diary_v1_diary_proto_rawDescData = file_mini_diary_v1_diary_proto_rawDesc
)

func file_mini_diary_v1_diary_proto_rawDescGZIP() []byte {
	file_mini_diary_v1_diary_proto_rawDescOnce.Do(func() {
		file_mini_diary_v1_diary_proto_rawDescData = protoimpl.X.CompressGZIP(file_mini_diary_v1_diary_proto_rawDescData)
	})
	return file_mini_diary_v1_diary_proto_rawDescData
}

var file_mini_diary_v1_diary_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_mini_diary_v1_diary_proto_goTypes = []any{
	(*DeleteDiaryReq)(nil),    // 0: api.mini.diary.v1.DeleteDiaryReq
	(*DeleteDiaryResp)(nil),   // 1: api.mini.diary.v1.DeleteDiaryResp
	(*UpdateDiaryReq)(nil),    // 2: api.mini.diary.v1.UpdateDiaryReq
	(*UpdateDiaryResp)(nil),   // 3: api.mini.diary.v1.UpdateDiaryResp
	(*CreateDiaryReq)(nil),    // 4: api.mini.diary.v1.CreateDiaryReq
	(*CreateDiaryResp)(nil),   // 5: api.mini.diary.v1.CreateDiaryResp
	(*GetDiaryReq)(nil),       // 6: api.mini.diary.v1.GetDiaryReq
	(*GetDiaryResp)(nil),      // 7: api.mini.diary.v1.GetDiaryResp
	(*ListDiaryReq)(nil),      // 8: api.mini.diary.v1.ListDiaryReq
	(*ListDiaryResp)(nil),     // 9: api.mini.diary.v1.ListDiaryResp
	(*ListItemDiaryResp)(nil), // 10: api.mini.diary.v1.ListItemDiaryResp
}
var file_mini_diary_v1_diary_proto_depIdxs = []int32{
	10, // 0: api.mini.diary.v1.ListDiaryResp.list:type_name -> api.mini.diary.v1.ListItemDiaryResp
	8,  // 1: api.mini.diary.v1.Diary.ListDiary:input_type -> api.mini.diary.v1.ListDiaryReq
	6,  // 2: api.mini.diary.v1.Diary.GetDiary:input_type -> api.mini.diary.v1.GetDiaryReq
	4,  // 3: api.mini.diary.v1.Diary.CreateDiary:input_type -> api.mini.diary.v1.CreateDiaryReq
	2,  // 4: api.mini.diary.v1.Diary.UpdateDiary:input_type -> api.mini.diary.v1.UpdateDiaryReq
	0,  // 5: api.mini.diary.v1.Diary.DeleteDiary:input_type -> api.mini.diary.v1.DeleteDiaryReq
	9,  // 6: api.mini.diary.v1.Diary.ListDiary:output_type -> api.mini.diary.v1.ListDiaryResp
	7,  // 7: api.mini.diary.v1.Diary.GetDiary:output_type -> api.mini.diary.v1.GetDiaryResp
	5,  // 8: api.mini.diary.v1.Diary.CreateDiary:output_type -> api.mini.diary.v1.CreateDiaryResp
	3,  // 9: api.mini.diary.v1.Diary.UpdateDiary:output_type -> api.mini.diary.v1.UpdateDiaryResp
	1,  // 10: api.mini.diary.v1.Diary.DeleteDiary:output_type -> api.mini.diary.v1.DeleteDiaryResp
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_mini_diary_v1_diary_proto_init() }
func file_mini_diary_v1_diary_proto_init() {
	if File_mini_diary_v1_diary_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mini_diary_v1_diary_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteDiaryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mini_diary_v1_diary_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteDiaryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mini_diary_v1_diary_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateDiaryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mini_diary_v1_diary_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateDiaryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mini_diary_v1_diary_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CreateDiaryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mini_diary_v1_diary_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*CreateDiaryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mini_diary_v1_diary_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetDiaryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mini_diary_v1_diary_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetDiaryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mini_diary_v1_diary_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ListDiaryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mini_diary_v1_diary_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ListDiaryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mini_diary_v1_diary_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*ListItemDiaryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mini_diary_v1_diary_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mini_diary_v1_diary_proto_goTypes,
		DependencyIndexes: file_mini_diary_v1_diary_proto_depIdxs,
		MessageInfos:      file_mini_diary_v1_diary_proto_msgTypes,
	}.Build()
	File_mini_diary_v1_diary_proto = out.File
	file_mini_diary_v1_diary_proto_rawDesc = nil
	file_mini_diary_v1_diary_proto_goTypes = nil
	file_mini_diary_v1_diary_proto_depIdxs = nil
}
