// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Diary is the predicate function for diary builders.
type Diary func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
